version: '3.1'
services:
  httpd:
    image: httpd:2.4
    restart: always
    ports:
      - 80:80
    volumes:
      - "./www:/usr/local/apache2/htdocs/"
      - "./conf/httpd.conf:/usr/local/apache2/conf/httpd.conf"